"""add_description_to_articles

Revision ID: 3587d5e33f2f
Revises: ab87165a001d
Create Date: 2026-08-03 15:23:48.857316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3587d5e33f2f'
down_revision: Union[str, Sequence[str], None] = 'ab87165a001d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'description')
    # ### end Alembic commands ###
