"""add_number_to_articles

Revision ID: 3caa62dff1c2
Revises: 9ebbdb70da12
Create Date: 2026-07-30 15:39:14.718294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3caa62dff1c2'
down_revision: Union[str, Sequence[str], None] = '9ebbdb70da12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('number', sa.Integer(), nullable=True))
    op.drop_index(op.f('idx_articles_search'), table_name='articles', postgresql_using='gin')
    op.create_unique_constraint(None, 'articles', ['number'])
    op.drop_column('articles', 'search_vector')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('search_vector', postgresql.TSVECTOR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'articles', type_='unique')
    op.create_index(op.f('idx_articles_search'), 'articles', ['search_vector'], unique=False, postgresql_using='gin')
    op.drop_column('articles', 'number')
    # ### end Alembic commands ###
