"""add embedding column to article

Revision ID: 6a66702d5247
Revises: ee997e2edc1b
Create Date: 2026-07-29 13:27:18.854643

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = "6a66702d5247"
down_revision = "0f2a34e18e9d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # Колонка уже существует — пропускаем
    connection = op.get_bind()
    result = connection.execute(
        sa.text(
            "SELECT column_name FROM information_schema.columns WHERE table_name='articles' AND column_name='embedding'"
        )
    )
    if not result.fetchone():
        op.add_column("articles", sa.Column("embedding", Vector(384), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "articles",
        sa.Column("search_vector", postgresql.TSVECTOR(), autoincrement=False, nullable=True),
    )
    op.create_index(
        op.f("idx_articles_search"),
        "articles",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.drop_column("articles", "embedding")
    # ### end Alembic commands ###
