"""add_source_to_articles

Revision ID: 9ebbdb70da12
Revises: 6a66702d5247
Create Date: 2026-07-29 14:10:49.711147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ebbdb70da12'
down_revision: Union[str, Sequence[str], None] = '6a66702d5247'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('source', sa.String(length=255), nullable=True))
    op.drop_index(op.f('idx_articles_search'), table_name='articles', postgresql_using='gin')
    op.drop_column('articles', 'search_vector')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('search_vector', postgresql.TSVECTOR(), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_articles_search'), 'articles', ['search_vector'], unique=False, postgresql_using='gin')
    op.drop_column('articles', 'source')
    # ### end Alembic commands ###
