"""add_category_closure

Revision ID: e5d3d64cb4df
Revises: 494354c6bc7b
Create Date: 2026-07-27 14:46:47.758933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5d3d64cb4df'
down_revision: Union[str, Sequence[str], None] = '494354c6bc7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_closure',
    sa.Column('ancestor_id', sa.Integer(), nullable=False),
    sa.Column('descendant_id', sa.Integer(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ancestor_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['descendant_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('ancestor_id', 'descendant_id')
    )
    op.add_column('categories', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'categories', 'categories', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'parent_id')
    op.drop_table('category_closure')
    # ### end Alembic commands ###
